# Generated by Django 4.2 on 2023-09-19 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MapAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradasedificacion',
            name='punto_camino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punto_camino', to='MapAdmin.punto'),
        ),
    ]
