# Generated by Django 4.2 on 2023-10-22 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MapAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='edificacion',
            name='informacion',
            field=models.TextField(max_length=3000, null=True),
        ),
    ]
